import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BookOpen,Search,Upload,Home,Brain,Gift,School,User,LogOut,ChevronRight,Plus,FileText,FlaskConical,Clock3,Star,ShieldCheck,Sparkles,Menu,X,ArrowRight,CheckCircle2,LockKeyhole,Mail,MapPin,Trophy,Settings,Trash2,Download,PlayCircle} from 'lucide-react';
import './styles.css';

const seedSchools=[
 {id:'bbl',name:'BBL Public School',city:'Agra',state:'Uttar Pradesh',country:'India',students:842},
 {id:'dpsd',name:'Delhi Public School',city:'Delhi',state:'Delhi',country:'India',students:1260},
 {id:'dav',name:'DAV Public School',city:'Jaipur',state:'Rajasthan',country:'India',students:734},
 {id:'stx',name:'St. Xavier’s School',city:'Kolkata',state:'West Bengal',country:'India',students:916}
];
const seedResources=[
 {id:1,title:'Nutrition in Plants — Quick Notes',subject:'Science',className:'Class 7',school:'BBL Public School',type:'Notes',author:'Aarav',points:35,downloads:128,created:'2h ago',color:'violet'},
 {id:2,title:'Integers Practice Worksheet',subject:'Mathematics',className:'Class 7',school:'BBL Public School',type:'Worksheet',author:'Meera',points:25,downloads:86,created:'5h ago',color:'blue'},
 {id:3,title:'The Mughal Empire — Revision Pack',subject:'Social Science',className:'Class 7',school:'Delhi Public School',type:'Revision',author:'Kabir',points:45,downloads:214,created:'1d ago',color:'amber'},
 {id:4,title:'English Grammar: Tenses Test',subject:'English',className:'Class 7',school:'BBL Public School',type:'Test',author:'Ananya',points:30,downloads:61,created:'1d ago',color:'emerald'},
 {id:5,title:'Heat & Temperature — Exam Questions',subject:'Science',className:'Class 7',school:'DAV Public School',type:'Question Bank',author:'Vihaan',points:40,downloads:174,created:'2d ago',color:'rose'}
];
const seedUsers={demo:{id:'demo',name:'Kunj',email:'demo@studentnetwork.app',password:'demo123',school:'BBL Public School',className:'Class 7',points:1240,streak:7}};

function App(){
 const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('sn_user')||'null'));
 const [users,setUsers]=useState(()=>JSON.parse(localStorage.getItem('sn_users')||JSON.stringify(seedUsers)));
 const [resources,setResources]=useState(()=>JSON.parse(localStorage.getItem('sn_resources')||JSON.stringify(seedResources)));
 const [schools,setSchools]=useState(()=>JSON.parse(localStorage.getItem('sn_schools')||JSON.stringify(seedSchools)));
 const [page,setPage]=useState('home'); const [auth,setAuth]=useState(null); const [mobile,setMobile]=useState(false); const [toast,setToast]=useState(null);
 useEffect(()=>localStorage.setItem('sn_users',JSON.stringify(users)),[users]);
 useEffect(()=>localStorage.setItem('sn_resources',JSON.stringify(resources)),[resources]);
 useEffect(()=>localStorage.setItem('sn_schools',JSON.stringify(schools)),[schools]);
 useEffect(()=>{if(user)localStorage.setItem('sn_user',JSON.stringify(user));else localStorage.removeItem('sn_user')},[user]);
 const notify=(msg,type='success')=>{setToast({msg,type});setTimeout(()=>setToast(null),2800)};
 const navigate=p=>{setPage(p);setMobile(false);window.scrollTo({top:0,behavior:'smooth'})};
 const login=(email,password)=>{const u=Object.values(users).find(x=>x.email.toLowerCase()===email.toLowerCase()&&x.password===password);if(!u)return false;setUser(u);setAuth(null);notify('Welcome back, '+u.name+'!');return true};
 const signup=data=>{if(Object.values(users).some(x=>x.email.toLowerCase()===data.email.toLowerCase()))return false;const u={id:crypto.randomUUID(),...data,points:100,streak:0};setUsers({...users,[u.id]:u});setUser(u);setAuth(null);notify('Account created — welcome to StudentNetwork!');return true};
 const addPoints=n=>{if(!user)return;const u={...user,points:(user.points||0)+n};setUser(u);setUsers(prev=>({...prev,[u.id]:u}))};
 return <div className="app">
   <Header user={user} page={page} navigate={navigate} openAuth={()=>setAuth('login')} logout={()=>{setUser(null);navigate('home');notify('Signed out')}} mobile={mobile} setMobile={setMobile}/>
   {page==='home'&&<HomePage user={user} navigate={navigate} schools={schools} resources={resources} openAuth={()=>setAuth('login')}/>} 
   {page==='explore'&&<Explore resources={resources} schools={schools} user={user} navigate={navigate}/>} 
   {page==='upload'&&<UploadPage user={user} schools={schools} addResource={r=>{setResources([r,...resources]);addPoints(r.points);notify('Upload published — points added!');navigate('library')}} openAuth={()=>setAuth('login')}/>} 
   {page==='library'&&<Library resources={resources} user={user} navigate={navigate}/>} 
   {page==='ai'&&<AIStudio user={user} openAuth={()=>setAuth('login')}/>} 
   {page==='rewards'&&<Rewards user={user} navigate={navigate} notify={notify}/>} 
   {page==='profile'&&<Profile user={user} schools={schools} setUser={setUser} setUsers={setUsers} navigate={navigate}/>} 
   {page==='request'&&<SchoolRequest schools={schools} setSchools={setSchools} notify={notify} navigate={navigate}/>} 
   <Footer navigate={navigate}/>
   {auth&&<AuthModal mode={auth} setMode={setAuth} login={login} signup={signup}/>} 
   {toast&&<div className={'toast '+toast.type}><CheckCircle2 size={18}/>{toast.msg}</div>}
 </div>
}

function Header({user,page,navigate,openAuth,logout,mobile,setMobile}){return <header className="header"><div className="nav wrap"><button className="brand" onClick={()=>navigate('home')}><span className="logo"><BookOpen size={22}/></span><span>Student<span className="brand-accent">Network</span></span></button><nav className={mobile?'navlinks open':'navlinks'}>{[['home','Home'],['explore','Explore'],['library','My Library'],['ai','AI Studio'],['rewards','Rewards']].map(([id,l])=><button key={id} className={page===id?'active':''} onClick={()=>navigate(id)}>{l}</button>)}</nav><div className="navright">{user?<><button className="points-pill" onClick={()=>navigate('rewards')}><Gift size={15}/>{user.points||0}</button><button className="avatar" onClick={()=>navigate('profile')}>{user.name?.[0]||'U'}</button><button className="desktop-only iconbtn" onClick={logout} title="Sign out"><LogOut size={18}/></button></>:<button className="signin" onClick={openAuth}>Sign in <ArrowRight size={16}/></button>}<button className="mobile-menu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div></div></header>}

function HomePage({user,navigate,schools,resources,openAuth}){return <main><section className="hero"><div className="hero-glow"/><div className="wrap hero-inner"><div className="eyebrow"><Sparkles size={15}/> The academic network built around your school</div><h1>Your school work.<br/><span>Your community.</span></h1><p>Find notes, worksheets and tests from students like you. Share what you know, earn points, and turn your syllabus into a smarter study plan with AI.</p><div className="hero-actions"><button className="primary" onClick={()=>navigate('explore')}>Explore your school <ArrowRight size={18}/></button><button className="secondary" onClick={user?()=>navigate('upload'):openAuth}><Upload size={17}/> Share your work</button></div><div className="trust"><div className="avatars"><i>AK</i><i>MS</i><i>RV</i><i>+</i></div><span><b>2,400+</b> students already learning together</span></div></div></section>
<section className="wrap stats"><Stat n="18K+" l="Study resources"/><Stat n="320+" l="Schools"/><Stat n="96K+" l="Helpful downloads"/><Stat n="4.9/5" l="Student rating"/></section>
<section className="wrap section"><div className="section-head"><div><div className="kicker">BUILT FOR STUDENTS</div><h2>Everything you need to study better</h2></div><button className="textbtn" onClick={()=>navigate('explore')}>View all <ChevronRight size={16}/></button></div><div className="feature-grid"><Feature icon={<School/>} title="Your school, first" text="Browse resources by country, state, city, school, class and subject." onClick={()=>navigate('explore')}/><Feature icon={<Upload/>} title="Share & earn" text="Upload useful work, help classmates and build your contributor score." onClick={()=>navigate('upload')}/><Feature icon={<Brain/>} title="AI Study Studio" text="Turn your syllabus and notes into revision packs, flashcards and tests." onClick={()=>navigate('ai')}/></div></section>
<section className="wrap section split"><div><div className="kicker">COMMUNITY LIBRARY</div><h2>What students are studying right now</h2><p className="muted">Realistic sample resources are included so you can test the complete flow immediately.</p></div><div className="mini-list">{resources.slice(0,3).map(r=><ResourceRow key={r.id} r={r} onClick={()=>navigate('library')}/>)}</div></section>
<section className="wrap cta"><div><div className="kicker">CAN'T FIND YOUR SCHOOL?</div><h2>We'll add it.</h2><p>Tell us where you study and we'll review the request.</p></div><button className="secondary" onClick={()=>navigate('request')}>Request a school <ArrowRight size={17}/></button></section>
</main>}
const Stat=({n,l})=><div><strong>{n}</strong><span>{l}</span></div>;
const Feature=({icon,title,text,onClick})=><button className="feature" onClick={onClick}><span className="feature-icon">{icon}</span><h3>{title}</h3><p>{text}</p><span className="feature-arrow"><ArrowRight size={17}/></span></button>;
function ResourceRow({r,onClick}){return <button className="resource-row" onClick={onClick}><span className={'docicon '+r.color}><FileText size={20}/></span><span className="grow"><b>{r.title}</b><small>{r.subject} · {r.className} · {r.author}</small></span><span className="row-points">+{r.points}</span><ChevronRight size={16}/></button>}

function Explore({resources,schools,user,navigate}){const [q,setQ]=useState('');const [country,setCountry]=useState('India');const [state,setState]=useState('All states');const [city,setCity]=useState('All cities');const [school,setSchool]=useState('All schools');const [subject,setSubject]=useState('All subjects');const filtered=resources.filter(r=>(!q||`${r.title} ${r.subject} ${r.school}`.toLowerCase().includes(q.toLowerCase()))&&(!school||school==='All schools'||r.school===school)&&(!subject||subject==='All subjects'||r.subject===subject));return <main className="wrap page"><div className="page-top"><div><div className="kicker">DISCOVER</div><h1>Find your school work</h1><p>Search by location and school, then filter down to exactly what you need.</p></div><button className="primary" onClick={()=>navigate(user?'upload':'home')}><Upload size={17}/> Upload resource</button></div><div className="searchbar"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search notes, worksheets, chapters..."/></div><div className="filters"><Select value={country} set={setCountry} options={['India','United States','United Kingdom']}/><Select value={state} set={setState} options={['All states','Uttar Pradesh','Delhi','Rajasthan','West Bengal']}/><Select value={city} set={setCity} options={['All cities','Agra','Delhi','Jaipur','Kolkata']}/><Select value={school} set={setSchool} options={['All schools',...schools.map(s=>s.name)]}/><Select value={subject} set={setSubject} options={['All subjects','Science','Mathematics','Social Science','English']}/></div><div className="school-chips">{schools.slice(0,4).map(s=><button key={s.id} onClick={()=>setSchool(s.name)}><School size={15}/><span>{s.name}<small>{s.city} · {s.students} students</small></span></button>)}</div><div className="results-head"><b>{filtered.length} resources</b><span>Sorted by helpfulness</span></div><div className="resource-grid">{filtered.map(r=><ResourceCard key={r.id} r={r}/>)}</div>{!filtered.length&&<Empty title="Nothing found" text="Try a different search or school filter."/>}</main>}
const Select=({value,set,options})=><select value={value} onChange={e=>set(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select>;
function ResourceCard({r}){return <article className="resource-card"><div className="card-top"><span className={'type '+r.color}>{r.type}</span><span className="points">+{r.points} pts</span></div><h3>{r.title}</h3><p>{r.subject} · {r.className}</p><div className="schoolline"><School size={14}/>{r.school}</div><div className="card-foot"><span><User size={13}/>{r.author}</span><span><Download size={13}/>{r.downloads}</span><span>{r.created}</span></div><button className="outline full"><PlayCircle size={15}/> Open resource</button></article>}

function UploadPage({user,schools,addResource,openAuth}){const [form,setForm]=useState({title:'',subject:'Science',className:user?.className||'Class 7',school:user?.school||schools[0].name,type:'Notes'});const [file,setFile]=useState(null);if(!user)return <AuthGate title="Share your work" text="Sign in to upload resources and earn contributor points." openAuth={openAuth}/>;const submit=e=>{e.preventDefault();if(!form.title.trim()||!file)return;addResource({id:Date.now(),...form,author:user.name,points:form.type==='Notes'?35:25,downloads:0,created:'just now',color:'violet'})};return <main className="wrap page narrow"><div className="page-top"><div><div className="kicker">CONTRIBUTE</div><h1>Share something useful</h1><p>Help another student and earn points for every quality contribution.</p></div><div className="earn"><Gift size={17}/> Earn up to <b>45 points</b></div></div><form className="form-card" onSubmit={submit}><label>Resource title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Light — Chapter 15 Quick Notes"/></label><div className="form-row"><label>Subject<Select value={form.subject} set={v=>setForm({...form,subject:v})} options={['Science','Mathematics','Social Science','English','Hindi','Computer']}/></label><label>Class<Select value={form.className} set={v=>setForm({...form,className:v})} options={['Class 6','Class 7','Class 8','Class 9','Class 10']}/></label></div><div className="form-row"><label>School<Select value={form.school} set={v=>setForm({...form,school:v})} options={schools.map(s=>s.name)}/></label><label>Type<Select value={form.type} set={v=>setForm({...form,type:v})} options={['Notes','Worksheet','Test','Revision','Question Bank']}/></label></div><label className="dropzone"><Upload size={28}/><b>{file?file.name:'Drop your file here'}</b><span>{file?'Ready to publish':'PDF, image or document · up to 10 MB'}</span><input type="file" accept=".pdf,.png,.jpg,.jpeg,.doc,.docx" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><div className="notice"><ShieldCheck size={17}/><span>Only upload work you have permission to share. StudentNetwork may moderate reported content.</span></div><button className="primary full" type="submit" disabled={!file||!form.title}>Publish resource <ArrowRight size={17}/></button></form></main>}

function AIStudio({user,openAuth}){const [tab,setTab]=useState('notes');const [topic,setTopic]=useState('Nutrition in Plants');const [grade,setGrade]=useState(user?.className||'Class 7');const [source,setSource]=useState('NCERT Science');const [generated,setGenerated]=useState(false);if(!user)return <AuthGate title="AI Study Studio" text="Sign in to create personalized notes, flashcards and tests." openAuth={openAuth}/>;const generate=()=>setGenerated(true);return <main className="wrap page"><div className="ai-hero"><div><div className="kicker">AI STUDY STUDIO</div><h1>Study material that matches <span>your syllabus.</span></h1><p>Give StudentNetwork your class, book and topic. The demo engine generates a structured study pack you can test now.</p></div><div className="ai-orb"><Brain size={42}/></div></div><div className="ai-layout"><aside className="ai-sidebar"><b>CREATE</b>{[['notes','Notes',FileText],['flashcards','Flashcards',Brain],['quiz','Quiz',FlaskConical],['exam','Mock exam',Clock3]].map(([id,l,I])=><button className={tab===id?'sel':''} onClick={()=>setTab(id)} key={id}><I size={17}/>{l}</button>)}<div className="ai-tip"><Sparkles size={17}/><b>Tip</b><p>Upload a syllabus photo in the full version to keep generation aligned with your school.</p></div></aside><section className="ai-builder"><div className="builder-head"><div><h2>{tab==='notes'?'Create notes':tab==='flashcards'?'Create flashcards':tab==='quiz'?'Create a quiz':'Create a mock exam'}</h2><span>Personalized for your profile</span></div><span className="pro-pill">PRO</span></div><div className="form-row"><label>Class<Select value={grade} set={setGrade} options={['Class 6','Class 7','Class 8','Class 9','Class 10']}/></label><label>Source book<input value={source} onChange={e=>setSource(e.target.value)}/></label></div><label>Topic or chapter<input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. Acids, Bases and Salts"/></label><label>What should the AI focus on?<textarea defaultValue="Exam-ready explanations, key definitions, examples and common mistakes."/></label><button className="primary full" onClick={generate}><Sparkles size={17}/> Generate study pack</button>{generated&&<Generated tab={tab} topic={topic} grade={grade}/>}</section></div></main>}
function Generated({tab,topic,grade}){const cards=tab==='flashcards'?['What is photosynthesis?','Why do leaves look green?','What is chlorophyll?','Where does a plant get carbon dioxide?','Define autotrophic nutrition.']:['Define autotrophic nutrition.','Explain photosynthesis in simple steps.','Name two raw materials required for photosynthesis.','What is the role of chlorophyll?'];return <div className="generated"><div className="generated-head"><div><span className="type violet">GENERATED</span><h3>{topic} · {grade}</h3></div><button className="outline">Save pack</button></div>{tab==='notes'?<><div className="answer"><h4>Quick revision</h4><p>Plants make their own food using light energy, carbon dioxide and water. Chlorophyll captures light energy, and glucose is produced during photosynthesis.</p></div><div className="answer"><h4>Remember</h4><ul><li>Photosynthesis happens mainly in green leaves.</li><li>Carbon dioxide enters through stomata.</li><li>Oxygen is released as a by-product.</li></ul></div></>:<div className="flash-preview">{cards.map((c,i)=><div key={i}><span>{i+1}</span><b>{c}</b><small>Tap to reveal answer</small></div>)}</div>}<div className="generated-note"><CheckCircle2 size={16}/> Generated content should be checked against your school textbook before an exam.</div></div>}

function Rewards({user,navigate,notify}){if(!user)return <AuthGate title="Rewards" text="Sign in to see your points, streak and rewards." openAuth={()=>{}}/>;const tiers=[['Bronze','500 pts','Profile badge'],['Silver','1,500 pts','Exclusive themes'],['Gold','3,000 pts','₹250 reward'],['Scholar','7,500 pts','₹750 reward']];return <main className="wrap page"><div className="rewards-banner"><div><div className="kicker">YOUR CONTRIBUTION</div><h1>{user.points||0} points</h1><p>Keep sharing useful work. Quality contributions move you up the leaderboard.</p></div><div className="trophy"><Trophy size={48}/></div></div><div className="reward-grid"><section className="panel"><h2>How points work</h2><div className="pointline"><Upload/>Upload notes <b>+35</b></div><div className="pointline"><FileText/>Upload worksheet <b>+25</b></div><div className="pointline"><Star/>Resource marked helpful <b>+5</b></div><div className="pointline"><Gift/>Daily study streak <b>+10</b></div></section><section className="panel"><h2>Reward levels</h2>{tiers.map((t,i)=><div className={'tier '+((user.points||0)>=parseInt(t[1])?'unlocked':'')} key={t[0]}><span>{i+1}</span><div><b>{t[0]}</b><small>{t[1]} · {t[2]}</small></div>{(user.points||0)>=parseInt(t[1])&&<CheckCircle2 size={18}/>}</div>)}</section></div><div className="notice"><ShieldCheck size={17}/><span>Reward redemption is a planned feature. In this MVP, points are simulated and no real gift cards are issued.</span></div></main>}

function Library({resources,navigate}){return <main className="wrap page"><div className="page-top"><div><div className="kicker">YOUR LIBRARY</div><h1>Saved & contributed</h1><p>Keep your study resources in one place.</p></div><button className="primary" onClick={()=>navigate('upload')}><Plus size={17}/> Add resource</button></div><div className="library-tabs"><button className="active">Saved resources <span>8</span></button><button>My uploads <span>3</span></button><button>Recent <span>12</span></button></div><div className="resource-grid">{resources.slice(0,6).map(r=><ResourceCard key={r.id} r={r}/>)}</div></main>}
function Profile({user,schools,setUser,setUsers,navigate}){if(!user)return <AuthGate title="Your profile" text="Sign in to manage your StudentNetwork profile." openAuth={()=>{}}/>;const save=e=>{e.preventDefault();setUsers(p=>({...p,[user.id]:user}));localStorage.setItem('sn_user',JSON.stringify(user));};return <main className="wrap page narrow"><div className="profile-head"><div className="big-avatar">{user.name?.[0]}</div><div><div className="kicker">PROFILE</div><h1>{user.name}</h1><p>{user.school} · {user.className}</p></div><div className="profile-stat"><b>{user.points||0}</b><span>points</span></div></div><form className="form-card" onSubmit={save}><h2>Account details</h2><label>Display name<input value={user.name} onChange={e=>setUser({...user,name:e.target.value})}/></label><label>Email<input value={user.email} disabled/></label><div className="form-row"><label>School<Select value={user.school} set={v=>setUser({...user,school:v})} options={schools.map(s=>s.name)}/></label><label>Class<Select value={user.className} set={v=>setUser({...user,className:v})} options={['Class 6','Class 7','Class 8','Class 9','Class 10']}/></label></div><button className="primary">Save changes</button></form><div className="danger"><Trash2 size={18}/><div><b>Account data</b><p>This demo stores your account in this browser only.</p></div></div></main>}
function SchoolRequest({schools,setSchools,notify,navigate}){const [form,setForm]=useState({name:'',city:'',state:'',country:'India'});const submit=e=>{e.preventDefault();if(!form.name)return;setSchools([...schools,{...form,id:Date.now(),students:0,pending:true}]);notify('School request submitted for review.');navigate('home')};return <main className="wrap page narrow"><div className="page-top"><div><div className="kicker">SCHOOL DIRECTORY</div><h1>Request a school</h1><p>Can't find your school? Send us the details and we'll review it.</p></div></div><form className="form-card" onSubmit={submit}><label>School name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Sunrise Public School"/></label><div className="form-row"><label>Country<input required value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/></label><label>State<input required value={form.state} onChange={e=>setForm({...form,state:e.target.value})}/></label></div><label>City<input required value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>Why should we add it? <textarea placeholder="Optional context or school website"/></label><button className="primary full">Submit request <ArrowRight size={17}/></button></form></main>}
const AuthGate=({title,text,openAuth})=><main className="authgate wrap"><div className="gate-icon"><LockKeyhole size={30}/></div><h1>{title}</h1><p>{text}</p><button className="primary" onClick={openAuth}>Sign in / create account <ArrowRight size={17}/></button></main>;
function AuthModal({mode,setMode,login,signup}){const [form,setForm]=useState(mode==='login'?{email:'demo@studentnetwork.app',password:'demo123'}:{name:'',email:'',password:'',school:'BBL Public School',className:'Class 7'});const [error,setError]=useState('');const submit=e=>{e.preventDefault();const ok=mode==='login'?login(form.email,form.password):signup(form);if(!ok)setError(mode==='login'?'Incorrect email or password. Try the demo account or sign up.':'An account with this email already exists.');};return <div className="modal-bg"><div className="modal"><button className="modal-close" onClick={()=>setMode(null)}><X/></button><div className="modal-logo"><span className="logo"><BookOpen size={20}/></span><b>Student<span>Network</span></b></div><h2>{mode==='login'?'Welcome back':'Create your account'}</h2><p>{mode==='login'?'Continue your learning journey.':'Join your school community in minutes.'}</p><form onSubmit={submit}>{mode==='signup'&&<label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name"/></label>}<label><Mail size={14}/> Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com"/></label><label>Password<input required minLength={6} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="At least 6 characters"/></label>{mode==='signup'&&<div className="form-row"><label>School<Select value={form.school} set={v=>setForm({...form,school:v})} options={seedSchools.map(s=>s.name)}/></label><label>Class<Select value={form.className} set={v=>setForm({...form,className:v})} options={['Class 6','Class 7','Class 8','Class 9','Class 10']}/></label></div>}{error&&<div className="error">{error}</div>}<button className="primary full">{mode==='login'?'Sign in':'Create account'} <ArrowRight size={16}/></button></form>{mode==='login'&&<div className="demo-login"><b>Demo account</b><span>demo@studentnetwork.app · demo123</span></div>}<p className="switch">{mode==='login'?"Don't have an account?":"Already have an account?"} <button onClick={()=>{setError('');setMode(mode==='login'?'signup':'login');setForm(mode==='login'?{name:'',email:'',password:'',school:'BBL Public School',className:'Class 7'}:{email:'demo@studentnetwork.app',password:'demo123'})}>{mode==='login'?'Sign up':'Sign in'}</button></p></div></div>}
const Empty=({title,text})=><div className="empty"><Search size={28}/><h3>{title}</h3><p>{text}</p></div>;
function Footer({navigate}){return <footer><div className="wrap footer-grid"><div><button className="brand footerbrand" onClick={()=>navigate('home')}><span className="logo"><BookOpen size={20}/></span>Student<span className="brand-accent">Network</span></button><p>Students helping students learn better.</p></div><div><b>Product</b><button onClick={()=>navigate('explore')}>Explore</button><button onClick={()=>navigate('ai')}>AI Studio</button><button onClick={()=>navigate('rewards')}>Rewards</button></div><div><b>Community</b><button onClick={()=>navigate('upload')}>Share work</button><button onClick={()=>navigate('request')}>Request school</button><button onClick={()=>navigate('profile')}>Profile</button></div><div><b>Note</b><p className="small">This prototype uses browser storage and simulated AI/reward flows. Connect a real auth/database/AI provider before accepting real users or payments.</p></div></div><div className="wrap copyright">© 2026 StudentNetwork · Built for learning together</div></footer>}

createRoot(document.getElementById('root')).render(<App/>);
