/* StudentNetwork Community Layer: chats, comments, collaborative edits and abuse controls. */
const SN_CHAT='sn_chat_v1', SN_COMMENTS='sn_comments_v1', SN_WORKS='sn_works_v1', SN_REPORTS='sn_reports_v1', SN_BANS='sn_bans_v1', SN_AUDIT='sn_audit_v1';
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const user=()=>read('sn_user',null);
const safe=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const uid=()=>`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const defaults=[
 {id:'w1',title:'Class 7 Science — Chapter 1 Notes',owner:'Riya',body:'Complete revision notes for the chapter.',version:1},
 {id:'w2',title:'Integers Practice Set',owner:'Aman',body:'Practice questions and answers.',version:1}
];
const ensure=()=>{if(!localStorage.getItem(SN_WORKS))write(SN_WORKS,defaults)};
function audit(action,target,meta={}){const u=user();const a=read(SN_AUDIT,[]);a.unshift({id:uid(),at:new Date().toISOString(),userId:u?.id||'guest',userName:u?.name||'Guest',action,target,meta});write(SN_AUDIT,a.slice(0,500));}
function isBanned(){const u=user();return !!u&&read(SN_BANS,[]).some(b=>b.userId===u.id&&b.permanent);}
function ban(userId,reason){const b=read(SN_BANS,[]);if(!b.some(x=>x.userId===userId&&x.permanent)){b.push({userId,reason,permanent:true,bannedAt:new Date().toISOString()});write(SN_BANS,b)}audit('PERMANENT_BAN',userId,{reason});}
function guard(){if(isBanned()){alert('Your StudentNetwork account is permanently banned for community-safety violations.');return false}return true}

const css=document.createElement('style');css.textContent=`
.sn-social{position:fixed;left:20px;bottom:20px;z-index:8999;border:0;border-radius:999px;padding:13px 17px;background:#0f172a;color:#fff;font-weight:900;box-shadow:0 14px 35px #0003;cursor:pointer}.sn-social-back{position:fixed;inset:0;z-index:10001;background:#08101fcc;backdrop-filter:blur(9px);display:grid;place-items:center;padding:18px}.sn-social-modal{width:min(980px,100%);max-height:92vh;overflow:auto;background:#fff;color:#111827;border-radius:25px;box-shadow:0 30px 100px #0005;font-family:Inter,system-ui,sans-serif}.sn-social-head{padding:23px 25px 15px;border-bottom:1px solid #e7e9ef;display:flex;justify-content:space-between;align-items:flex-start}.sn-social-head h2{margin:4px 0}.sn-social-head p{margin:0;color:#697386;font-size:13px}.sn-x{border:0;background:#f1f3f7;border-radius:10px;width:38px;height:38px;font-size:21px}.sn-tabs{display:flex;gap:7px;padding:13px 20px;border-bottom:1px solid #eee;overflow:auto}.sn-tab{border:0;background:#f3f4f7;padding:9px 13px;border-radius:10px;font-weight:800;white-space:nowrap;cursor:pointer}.sn-tab.active{background:#111827;color:white}.sn-content{padding:20px}.sn-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.sn-card{border:1px solid #e5e7eb;border-radius:17px;padding:16px;background:#fafbfc}.sn-card h3{margin:0 0 6px;font-size:17px}.sn-muted{color:#727b8d;font-size:12px}.sn-list{display:grid;gap:9px;margin-top:12px}.sn-item{border:1px solid #e5e7eb;border-radius:13px;padding:12px;background:white}.sn-item b{font-size:13px}.sn-item small{display:block;color:#7a8393;margin-top:3px}.sn-row{display:flex;gap:8px;align-items:center}.sn-row input,.sn-row textarea,.sn-card select{width:100%;box-sizing:border-box;border:1px solid #dce0e8;border-radius:10px;padding:10px;outline:none}.sn-row textarea{min-height:76px;resize:vertical}.sn-primary,.sn-danger{border:0;border-radius:10px;padding:10px 13px;font-weight:900;cursor:pointer}.sn-primary{background:#111827;color:#fff}.sn-danger{background:#fee2e2;color:#991b1b}.sn-badge{display:inline-block;font-size:10px;font-weight:900;padding:5px 7px;border-radius:8px;background:#eef2ff;color:#4338ca}.sn-warning{background:#fff7ed;border:1px solid #fed7aa;color:#9a3412;padding:11px;border-radius:11px;font-size:12px;line-height:1.5;margin-bottom:14px}@media(max-width:700px){.sn-grid{grid-template-columns:1fr}.sn-social{left:14px;bottom:14px}}
`;document.head.appendChild(css);

function openHub(){if(document.querySelector('.sn-social-back'))return;if(!guard())return;ensure();const back=document.createElement('div');back.className='sn-social-back';const modal=document.createElement('section');modal.className='sn-social-modal';back.appendChild(modal);document.body.appendChild(back);
let tab='chat';
const render=()=>{const chats=read(SN_CHAT,[]),comments=read(SN_COMMENTS,[]),works=read(SN_WORKS,defaults),reports=read(SN_REPORTS,[]);modal.innerHTML=`<div class="sn-social-head"><div><span class="sn-badge">COMMUNITY + SAFETY</span><h2>StudentNetwork Community</h2><p>Talk, comment, improve work together — with a visible safety trail.</p></div><button class="sn-x">×</button></div><div class="sn-tabs"><button class="sn-tab ${tab==='chat'?'active':''}" data-tab="chat">💬 Chat</button><button class="sn-tab ${tab==='comments'?'active':''}" data-tab="comments">🗨 Comments</button><button class="sn-tab ${tab==='changes'?'active':''}" data-tab="changes">✏️ Improve Work</button><button class="sn-tab ${tab==='safety'?'active':''}" data-tab="safety">🛡 Safety</button></div><div class="sn-content">${body(tab,{chats,comments,works,reports})}</div>`;
modal.querySelector('.sn-x').onclick=()=>back.remove();modal.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>{tab=x.dataset.tab;render()});bind(tab,modal);};
function body(t,d){if(t==='chat')return `<div class="sn-grid"><div class="sn-card"><h3>Community chat</h3><div class="sn-muted">Keep it school-friendly. Never share passwords, phone numbers or private addresses.</div><div class="sn-list" id="sn-chat-list">${d.chats.slice(-15).map(x=>`<div class="sn-item"><b>${safe(x.name)}</b><small>${safe(x.text)}</small></div>`).join('')||'<div class="sn-muted">No messages yet. Start the study conversation.</div>'}</div></div><div class="sn-card"><h3>Send message</h3><div class="sn-row"><textarea id="sn-chat-text" placeholder="Ask a study question or help someone..."></textarea></div><br><button class="sn-primary" data-send-chat>Send</button></div></div>`;
if(t==='comments')return `<div class="sn-card"><h3>Work comments</h3><div class="sn-muted">Use comments to point out missing steps, unclear answers or useful improvements.</div><div class="sn-list">${d.comments.slice(-20).map(x=>`<div class="sn-item"><b>${safe(x.name)} · ${safe(x.workTitle)}</b><small>${safe(x.text)}</small></div>`).join('')||'<div class="sn-muted">No comments yet.</div>'}</div><br><div class="sn-row"><select id="sn-comment-work">${d.works.map(w=>`<option value="${w.id}">${safe(w.title)}</option>`).join('')}</select><input id="sn-comment-text" placeholder="Write a constructive comment..."></div><br><button class="sn-primary" data-send-comment>Post comment</button></div>`;
if(t==='changes')return `<div class="sn-grid"><div class="sn-card"><h3>Request / make an improvement</h3><p class="sn-muted">If a work is incomplete, another student can suggest a concrete change. The owner can approve it; approved edits become a new version instead of silently overwriting someone's work.</p><select id="sn-change-work">${d.works.map(w=>`<option value="${w.id}">${safe(w.title)} · v${w.version}</option>`).join('')}</select><br><br><textarea id="sn-change-text" placeholder="What is missing? What would you add or correct?"></textarea><br><br><button class="sn-primary" data-submit-change>Submit improvement</button></div><div class="sn-card"><h3>Version-safe collaboration</h3><div class="sn-list">${d.works.map(w=>`<div class="sn-item"><b>${safe(w.title)}</b><small>Owner: ${safe(w.owner)} · Version ${w.version}</small><button class="sn-primary" style="margin-top:8px" data-approve="${w.id}">Approve latest suggestion</button></div>`).join('')}</div></div></div>`;
return `<div class="sn-warning"><b>Permanent-ban policy:</b> malicious deletion, vandalism, spam, harassment, account abuse or deliberate attempts to destroy community data can lead to a permanent ban. Accidental mistakes should be reported and fixed — the system does not treat every mistake as malicious.</div><div class="sn-grid"><div class="sn-card"><h3>Report something</h3><select id="sn-report-type"><option>Spam</option><option>Harassment</option><option>Malicious deletion</option><option>Unsafe/private information</option><option>Other</option></select><br><br><textarea id="sn-report-text" placeholder="Describe what happened and where..."></textarea><br><br><button class="sn-danger" data-report>Submit report</button></div><div class="sn-card"><h3>Audit trail</h3><div class="sn-muted">Important actions are logged locally in this prototype so moderation can later become server-enforced.</div><div class="sn-list">${read(SN_AUDIT,[]).slice(0,8).map(a=>`<div class="sn-item"><b>${safe(a.action)}</b><small>${safe(a.userName)} · ${new Date(a.at).toLocaleString()}</small></div>`).join('')||'<div class="sn-muted">No actions logged yet.</div>'}</div></div></div>`}
function bind(t,m){const u=user();if(t==='chat')m.querySelector('[data-send-chat]').onclick=()=>{if(!guard())return;const el=m.querySelector('#sn-chat-text'),v=el.value.trim();if(!v)return;const a=read(SN_CHAT,[]);a.push({id:uid(),userId:u?.id||'guest',name:u?.name||'Guest',text:v,at:Date.now()});write(SN_CHAT,a.slice(-200));audit('CHAT_POST','community');render()};if(t==='comments')m.querySelector('[data-send-comment]').onclick=()=>{if(!guard())return;const text=m.querySelector('#sn-comment-text').value.trim(),id=m.querySelector('#sn-comment-work').value;if(!text)return;const w=read(SN_WORKS,defaults).find(x=>x.id===id);const a=read(SN_COMMENTS,[]);a.push({id:uid(),userId:u?.id||'guest',name:u?.name||'Guest',workId:id,workTitle:w?.title||'Work',text,at:Date.now()});write(SN_COMMENTS,a.slice(-300));audit('COMMENT_POST',id);render()};if(t==='changes')m.querySelector('[data-submit-change]').onclick=()=>{if(!guard())return;const id=m.querySelector('#sn-change-work').value,text=m.querySelector('#sn-change-text').value.trim();if(!text)return;const w=read(SN_WORKS,defaults).find(x=>x.id===id);const a=read('sn_change_requests_v1',[]);a.push({id:uid(),workId:id,workTitle:w?.title||'Work',requesterId:u?.id||'guest',requesterName:u?.name||'Guest',text,status:'pending',at:Date.now()});write('sn_change_requests_v1',a.slice(-200));audit('CHANGE_REQUEST',id);alert('Improvement submitted. In the production backend, the owner/moderator will approve it before the work is changed.');render()};m.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>{if(!guard())return;const id=b.dataset.approve,changes=read('sn_change_requests_v1',[]).filter(x=>x.workId===id&&x.status==='pending');if(!changes.length)return alert('No pending improvement for this work.');const a=read(SN_WORKS,defaults);const w=a.find(x=>x.id===id);w.version=(w.version||1)+1;w.lastImprovement=changes[changes.length-1].text;w.updatedAt=Date.now();changes.forEach(c=>c.status='approved');write(SN_WORKS,a);const all=read('sn_change_requests_v1',[]);all.forEach(c=>{if(c.workId===id&&c.status==='pending')c.status='approved'});write('sn_change_requests_v1',all);audit('WORK_VERSION_APPROVED',id,{version:w.version});render()});if(t==='safety')m.querySelector('[data-report]').onclick=()=>{if(!guard())return;const text=m.querySelector('#sn-report-text').value.trim(),type=m.querySelector('#sn-report-type').value;if(!text)return;const a=read(SN_REPORTS,[]);a.push({id:uid(),reporterId:u?.id||'guest',type,text,at:Date.now(),status:'open'});write(SN_REPORTS,a.slice(-300));audit('REPORT_SUBMITTED',type);alert('Report recorded. A moderator should review it before any permanent ban.');render()}}
render();back.addEventListener('click',e=>{if(e.target===back)back.remove()});}
function install(){if(!document.querySelector('[data-sn-community]')){const b=document.createElement('button');b.className='sn-social';b.dataset.snCommunity='1';b.textContent='💬 Community';b.onclick=openHub;document.body.appendChild(b)}}
new MutationObserver(install).observe(document.documentElement,{childList:true,subtree:true});setTimeout(install,900);ensure();
